<a href="https://colab.research.google.com/github/ravbuilds/numpy-deep-dive/blob/main/NumpyOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy Operation**
This notebook provides deep down in NumPy library and various operations we can perform on the **ndarray object**.
We will cover following topics in this notebook.

- **Creating NumPy Arrays**
- **Properties & Attributes**
- **Python List vs Numpy Array**
- **Indexing, Slicing and Iteration**
- **Numpy Operations**
- **Reshaping Arrays**
- **Fancy Indexing**



### **Creating Arrays**
There are 6 different ways to create NumPy arrays:
1. Using np.array()
2. Using np.zero(), np.ones(), np.empty(), np.random()
3. Using np.arange()
4. Uing np.linspace()
5. Using Copy()
6. Using Identity()

In [2]:
import numpy as np

In [ ]:
# Generates a vector
one_dim = [1,2,3,4,5]
arr = np.array(one_dim)
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# Generates a 2D matrix
two_dim = [[1,2,3,4,5], [6,7,8,9, 0]]
two_dim_ndarray = np.array(two_dim)
two_dim_ndarray

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
# Generates matrix of 0's
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Generates matrix of 1's
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Generates an identity matrix
identity = np.identity(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Generates an array in the range of [start, stop)
arr_range = np.arange(1, 10)
arr_range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Generates an array/matrix of equidistant points or Returns evenly spaced numbers
equi_array = np.linspace(10, 20, 15)
equi_array

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

In [ ]:
# Generates a copy of the numpy array
identity_copy = identity.copy()
identity_copy

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###**Properties & Attributes**
Numpy array is a data type and will have properties and attributes. Some of these are listed here:
1. shape - reutrns a tuple of array dimension.
2. ndim
3. size
4. itemsize
5. dtype
6. astype()

In [ ]:
print(f"Array {arr} has shape {arr.shape}")
print(f"Dimension: {arr.ndim} dimension matrix")
print(f"Size: {arr.size}")
print(f"ItemSize: {arr.itemsize}")
print(f"Dtype: {arr.dtype}")

Array [1 2 3 4 5] has shape (5,)
Dimension: 1 dimension matrix
Size: 5
ItemSize: 8
Dtype: int64


In [ ]:
print(f"Array {two_dim_ndarray} has shape {two_dim_ndarray.shape}")
print(f"Dimension: {two_dim_ndarray.ndim} dimension matrix")
print(f"Size: {two_dim_ndarray.size}")
print(f"ItemSize: {two_dim_ndarray.itemsize}")
print(f"Dtype: {two_dim_ndarray.dtype}")

Array [[1 2 3 4 5]
 [6 7 8 9 0]] has shape (2, 5)
Dimension: 2 dimension matrix
Size: 10
ItemSize: 8
Dtype: int64


In [ ]:
arr_3d = np.array([[[1,3], [5, 7]], [[2, 4], [4, 6]]])
print(f"Array {arr_3d} has shape {arr_3d.shape}")
print(f"Dimension: {arr_3d.ndim} dimension matrix")
print(f"Size: {arr_3d.size}")
print(f"ItemSize: {arr_3d.itemsize}")
print(f"Dtype: {arr_3d.dtype}")

Array [[[1 3]
  [5 7]]

 [[2 4]
  [4 6]]] has shape (2, 2, 2)
Dimension: 3 dimension matrix
Size: 8
ItemSize: 8
Dtype: int64


In [ ]:
# Convert data type of numpy array
print(f"Before converting data type: {arr_3d}")
arr_3d = arr_3d.astype('float')
print(f"After converting data type: {arr_3d}")

Before converting data type: [[[1 3]
  [5 7]]

 [[2 4]
  [4 6]]]
After converting data type: [[[1. 3.]
  [5. 7.]]

 [[2. 4.]
  [4. 6.]]]


### Numpy Array vs Python Lists
Numpy Array are:
1. Faster
2. Convienent
3. Less Memory

In [ ]:
py_list = range(100)
np_arr = np.arange(100)

#### Memory Comparison

In [ ]:
# Memory comparison between python list and numpy array
import sys
ONE_MB = 1024 * 1024

mem_python_list = sys.getsizeof(85) * len(py_list)
mem_numpy_arr = np_arr.size * np_arr.itemsize
print(f"memory for 100 item python list {mem_python_list} bytes")
print(f"memory for 100 item numpy array {mem_numpy_arr} bytes")
print(f"100K items: memory -> python list: {(100000 * mem_python_list)/ONE_MB} MB")
print(f"100K items: memory -> numpy arr: {(100000 * mem_numpy_arr)/ONE_MB} MB")

memory for 100 item python list 2800 bytes
memory for 100 item numpy array 800 bytes
100K items: memory -> python list: 267.02880859375 MB
100K items: memory -> numpy arr: 76.2939453125 MB


#### Efficiency Comparison

In [ ]:
import time
x = range(100000)
y = range(100000, 200000)

start_time = time.time() # start time
result = [x + y for x, y in zip(x, y)]
end_time = time.time() # end time
print(f"Time Spent: {end_time-start_time} seconds")

Time Spent: 0.01148080825805664


In [ ]:
x1 = np.arange(100000)
y1 = np.arange(100000, 200000)
start_time = time.time() # start time
result = x1 + y1
end_time = time.time() # end time
print(f"Time Spent: {end_time-start_time} seconds")

Time Spent: 0.0030364990234375 seconds


### Indexing, Slicing and Iteration

### Numpy Operations

### Reshaping Numpy Arrays
We can use following method to change the shape of the ndarrays. Here are 5 methods:
1. Ravel -> convert higher dimensional arrays into 1D arrays.
2. Reshape -> changes the shape of the array to other dimensions.
3. Transpose -> Column to Row and vice versa
4. Stacking -> Combine two same shape arrays using following functions:
- hstack
- vstack
5. Splitting -> Split array into multiple arrays
- hsplit
- vsplit

In [4]:
# Ravel is similar to nditer.
arr = np.arange(24).reshape(4, 6)
print("Before Ravel operations")
print(f"arr: {arr} has shape {arr.shape} and is {arr.ndim} dimension")
arr_ravel = arr.ravel()
print("After Ravel operations")
print(f"Ravel arr: {arr_ravel} has shape {arr_ravel.shape} and is {arr_ravel.ndim} dimension")

Before Ravel operations
arr: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] has shape (4, 6) and is 2 dimension
After Ravel operations
Ravel arr: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] has shape (24,) and is 1 dimension


In [6]:
# Transpose
print(f"Original array:\n {arr}")
print(f"Transpose array:\n {arr.transpose()}")


Original array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Transpose array:
 [[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [11]:
# Stacking --> hstack and vstack
arr5 = np.arange(0, 6).reshape(2, 3)
arr6 = np.arange(6, 12).reshape(2,3)
print("Before stacking")
print(f"arr5: {arr5}")
print()
print(f"arr6: {arr6}")
print("\n Horizontal Stacking")
print(np.hstack((arr5, arr6)))
print("\n Vertical Stacking")
print(np.vstack((arr5, arr6)))

Before stacking
arr5: [[0 1 2]
 [3 4 5]]

arr6: [[ 6  7  8]
 [ 9 10 11]]

 Horizontal Stacking
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]

 Vertical Stacking
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### Fancy Indexing

In [12]:
arr8 = np.arange(24).reshape(6,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
# Custom indexing -> need specific rows which are not continuous
arr8[[0, 2, 4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

### Indexing with boolean arrays

In [16]:
arr = np.random.randint(low=1, high=100, size=20).reshape(4, 5)
arr

array([[36, 53, 83, 80, 35],
       [40, 41, 66, 63, 81],
       [73, 57, 35,  3, 17],
       [24, 62, 38, 70, 67]])

In [17]:
# Generate boolean array from array.
# In this case we will use comparison operators to do element wise comparison.
arr > 50

array([[False,  True,  True,  True, False],
       [False, False,  True,  True,  True],
       [ True,  True, False, False, False],
       [False,  True, False,  True,  True]])

In [23]:
# indexing using Boolean arrays - aka Filtering
print(f"Output element > 50: {arr[arr>50]}")
print(f"Output element > 50 and Odd nubers: {arr[(arr>50) & (arr%2 != 0)]}")
print(f"Set element > 50 and Odd nubers to 0")
arr[(arr>50) & (arr%2 != 0)] = 0


Output element > 50: [80 66 62 70]
Output element > 50 and Odd nubers: []
Set element > 50 and Odd nubers to 0
